name = "miyako-web"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

# Custom domain routing
[[routes]]
pattern = "miyako-enterprises.com/*"
zone_name = "miyako-enterprises.com"
